export  const cardData = [
  {
    id: 1,
    src: "../src/assets/images/image-waffle-mobile.jpg",
    mainAlt: "waffle",
    category: "waffle",
    title: "Waffle with Berries",
    price: "6.50",
    cartImg: "../src/assets/images/icon-add-to-cart.svg",
    cartAlt: "cart-icon",
  },
  {
    id: 2,
    src: "../src/assets/images/image-creme-brulee-mobile.jpg",
    alt: "creme-brulee",
    category: "Creme Brulee",
    title: "Vanilla Bean Creme Brulee",
    price: "7.00",
    cartImg: "../src/assets/images/icon-add-to-cart.svg",
    cartAlt: "cart-icon",
  },
  {
    id: 3,
    src: "../src/assets/images/image-macaron-mobile.jpg",
    alt: "macaron",
    category: "Macaron",
    title: "Macaron Mix of Five",
    price: "8.00",
    cartImg: "../src/assets/images/icon-add-to-cart.svg",
    cartAlt: "cart-icon",
  },
  {
    id: 4,
    src: "../src/assets/images/image-tiramisu-mobile.jpg",
    alt: "tiramisu",
    category: "Tiramisu",
    title: "Classic Tiramisu",
    price: "5.50",
    cartImg: "../src/assets/images/icon-add-to-cart.svg",
    cartAlt: "cart-icon",
  },
  {
    id: 5,
    src: "../src/assets/images/image-baklava-mobile.jpg",
    alt: "baklava",
    category: "Baklava",
    title: "Pistachio Baklava",
    price: "4.00",
    cartImg: "../src/assets/images/icon-add-to-cart.svg",
    cartAlt: "cart-icon",
  },
  {
    id: 6,
    src: "../src/assets/images/image-meringue-mobile.jpg",
    alt: "meringue",
    category: "Pie",
    title: "Lemon Meringue Pie",
    price: "5.00",
    cartImg: "../src/assets/images/icon-add-to-cart.svg",
    cartAlt: "cart-icon",
  },
  {
    id: 7,
    src: "../src/assets/images/image-cake-mobile.jpg",
    alt: "cake",
    category: "Cake",
    title: "Red Velvet Cake",
    price: "4.50",
    cartImg: "../src/assets/images/icon-add-to-cart.svg",
    cartAlt: "cart-icon",
  },
  {
    id: 8,
    src: "../src/assets/images/image-brownie-mobile.jpg",
    alt: "brownie",
    category: "Brownie",
    title: "Salted Caramel Brownie",
    price: "5.50",
    cartImg: "../src/assets/images/icon-add-to-cart.svg",
    cartAlt: "cart-icon",
  },
  {
    id: 9,
    src: "../src/assets/images/image-panna-cotta-mobile.jpg",
    alt: "panna-cotta",
    category: "Panna Cotta",
    title: "Vanilla Panna Cotta",
    price: "6.50",
    cartImg: "../src/assets/images/icon-add-to-cart.svg",
    cartAlt: "cart-icon",
  },
];
